name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Lint code
      run: npm run lint
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        wait-on: 'https://povio-at.herokuapp.com'
        wait-on-timeout: 120
        browser: chrome
      env:
        CYPRESS_baseUrl: https://povio-at.herokuapp.com
        # For assignment demo - using test credentials
        # In production, these should be stored as GitHub secrets
        CYPRESS_EMAIL: bujare@gmail.com
        CYPRESS_PASSWORD: "12345678"
        CYPRESS_TEST_USER_NAME: Test User
        CYPRESS_EXISTING_USER_EMAIL: bujare@gmail.com
        CYPRESS_EXISTING_USER_PASSWORD: "12345678"
        CYPRESS_INVALID_EMAIL: invalid-email
        CYPRESS_VALID_PASSWORD: SecurePass123
        CYPRESS_MISMATCHED_PASSWORD: DifferentPass456
        CYPRESS_CAMPAIGN_NAME: Test Campaign
        CYPRESS_CAMPAIGN_DESCRIPTION: This is a test campaign for automation
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-reports
        path: |
          cypress/reports/
          cypress/screenshots/
          cypress/videos/
        retention-days: 30